ECommerceWebsite/Controllers/ProductCatController.cs
using ECommerceWebsite.Models;
using ECommerceWebsite.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;

namespace ECommerceWebsite.Controllers
{
    public class ProductCatController : Controller
    {
        private readonly IProductCatService service;
        public ProductCatController(IProductCatService service)
        {
            this.service = service;
        }

        public ActionResult Index()
        {
            return View(service.GetAllCat());
        }

        // GET: ProductCatController/Details/5
        public ActionResult Details(int id)
        {
            var cat = service.GetCatById(id);
            return View(cat);
        }

        // GET: ProductCatController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductCatController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductCat cat)
        {
            try
            {
                int result =service.AddCat(cat);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductCatController/Edit/5
        public ActionResult Edit(int id)
        {
            var cat = service.GetCatById(id);
            return View(cat);
        }

        // POST: ProductCatController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductCat cat)
        {
            try
            {
                int result = service.UpdateCat(cat);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductCatController/Delete/5
        public ActionResult Delete(int id)
        {
            var cat = service.GetCatById(id);
            return View(cat);
        }

        // POST: ProductCatController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                int result = service.DeleteCat(id);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

ECommerceWebsite/Controllers/UserController.cs
using ECommerceWebsite.Models;
using ECommerceWebsite.Service;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ECommerceWebsite.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService service;
        public UserController(IUserService service)
        {
            this.service = service;
        }

        // GET: UserController
        public ActionResult Index()
        {
            return View(service.GetAllUser());
        }

        // GET: UserController/Details/5
        public ActionResult Details(int id)
        {
            var user = service.GetUserById(id);
            return View(user);
        }
       

        // GET: UserController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            try
            {
                int result = service.AddUser(user);
                if (result == 1)
                    return RedirectToAction(nameof(Login));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Edit/5
        public ActionResult Edit(int id)
        {
            var user = service.GetUserById(id);
            return View(user);
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            try
            {
                int result = service.UpdateUser(user);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: UserController/Delete/5
        public ActionResult Delete(int id)
        {
            var user = service.GetUserById(id);
            return View(user);
        }

        // POST: UserController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                int result = service.DeleteUser(id);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Login()
        {
            
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
      

        public ActionResult Login(User user)
        {
            User u = service.GetUserByEmail(user.Email);
            try
            {
                if (u != null)
                {
                    if(u.Password==user.Password)
                    {
                        HttpContext.Session.SetString("RoleId", u.RoleId.ToString());
                        HttpContext.Session.SetString("UserId", u.Id.ToString());
                        if (u.RoleId==1)
                        {
                           
                            return RedirectToAction("Index","UserProduct");
                        }
                        else
                        {
                            return RedirectToAction("Index","Product");
                        }
                    }
                    else
                    {
                        ViewBag.errormassage = "Username or Password is incorrect";
                        return View();
                    }
                }
            }
            catch
            {
                return View();
            }
            return View();
            
            
        }
        public ActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return View("Login");
        }
    }
}

ECommerceWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ECommerceWebsite</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ECommerceWebsite.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerceWebsite</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        @if (HttpContextAccessor.HttpContext.Session.GetString("RoleId") == "2")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="ProductCat" asp-action="Index">Category</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                        }
                        @if (HttpContextAccessor.HttpContext.Session.GetString("RoleId") == "1")
                        {
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="UserProduct" asp-action="Index">Products</a>
                            </li>
                        }

                    </ul>
                    <ul class ="navbar-nav flex-grow-1 ml-auto">
                        @if (string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("UserId")))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create">Create User</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login User</a>
                            </li>
                        }
                         @if (!string.IsNullOrEmpty(HttpContextAccessor.HttpContext.Session.GetString("UserId"))){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogOut">Log Out</a>
                        </li>
                         }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ECommerceWebsite - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>